spring:
  datasource:
    url: jdbc:mysql://localhost:3307/quiz?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: blueflame0203
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
